### ISSUE TITLE
Edge Property

### ISSUE THREAD

**Issue by tommykennedy** [appscot/sails-orientdb#130]
Hi Dario,

Is it possible to save a property on an edge using many-to-many associations?

I know you can do it using the createEdge method. 

Regards
Tom

**Comment by dmarcelino** [comment]
Hi @tommykennedy, currently waterline does not provide an API for such. That would likely need to be done using a Many-to-many through association, which is not yet officially supported. Check balderdashy/waterline#705 for more details.

**Comment by tommykennedy** [comment]
Any idea when they would take such a feature on? Is waterline still actively being developed. I have seen waterline2 from Mike.

**Comment by dmarcelino** [comment]
> Any idea when they would take such a feature on?

It's hard to say since waterline is a community project developed voluntarily during people's free time, BTW do you want to contribute? :grinning: But anyway, this feature is in milestone `0.11`, the next major release.

> Is waterline still actively being developed.

Have you checked the [commit logs](https://github.com/balderdashy/waterline/commits/master)? It's definitely active! Check the commits chart:
<img width="921" alt="screen shot 2015-08-21 at 13 48 50" src="https://cloud.githubusercontent.com/assets/1280446/9408489/687bbf5e-480b-11e5-9b00-ea85556d7f48.png">

> I have seen waterline2 from Mike.

waterline2 aimed at re-writing some bits, some of it was already merged to waterline, other parts weren't and I (personal opinion) don't think they will. Mike has been busy with treeline and in the meanwhile waterline has changed significantly so it will be difficult to merge things from waterline2 back to waterline.

**Comment by tommykennedy** [comment]
Happy to contribute when I feel confident that I'm not a hindrance. Thanks Again for your answers. Much appreciated.
