### ISSUE TITLE
Fetch array of ids like collection

### ISSUE THREAD

**Issue by nomi-ramzan** [appscot/sails-orientdb#155]
Hi
I am trying to fetch an array of ids like linkList or linkSet basically i have this model
`clientIds:{ type:'array' }`
I am saving record ids(@rid) in it. Is there any way to fetch these records ? like `model.find().populate('clientid')`
Or something like this
`model.find().explore|visit('clientid')`

Thank you

**Comment by dmarcelino** [comment]
Hi @nomi-ramzan, you won't be able to do it in a single query. You'll need to pull the array with the rids first and then fetch the records that match the rids. Alternatively you can use the [`query()`](https://github.com/appscot/sails-orientdb#query-query--options-cb) method and use a SQL query or try to achieve this using the `orientjs` via the [`native()`](https://github.com/appscot/sails-orientdb#native-) method.

In order to use `populate()` you'll need to use Associations. More about this in the [readme](https://github.com/appscot/sails-orientdb#associations).

**Comment by nomi-ramzan** [comment]
Can you please help me in orient query ?
