### ISSUE TITLE
in my sails js application my show and edit function is working without # in id but not working with # id

### ISSUE THREAD

**Issue by gmchaturvedi1** [appscot/sails-orientdb#87]
in my sails js application my show and edit function is working without # in id but not working with # id

**Comment by dmarcelino** [comment]
Hi @gmchaturvedi1, can you provide more information? Code examples and model definitions perhaps? Id in the form `'#1:1'` should always work.

**Comment by gmchaturvedi1** [comment]
my model definittion is as follow:

/**
* User.js
*
* @description :: TODO: You might write a short summary of how this model works and what it represents here.
* @docs        :: http://sailsjs.org/#!documentation/models
*/

module.exports = {
  schema:true,
  attributes: {
    name:{
      type:'string'
    },
    title:{
      type:'string'
    },
    email:{
      type:'string',
      required:true

    },
    encryptedPassword:{
      type:'string'
    }

  },
  beforeCreate:function(values,next){
    if(!values.password||values.password!=values.confirmation){
      return next({err:"Password does Not math password confirmation"})
    }
    require('bcrypt').hash(values.password,10,function passwordEncrypted(err,encryptedPassword){
      if(err) return next(err);
      values.encryptedPassword=encryptedPassword;
      next();
    })

  }
};

**Comment by dmarcelino** [comment]
@gmchaturvedi1, can you show the code where you query the model by id? Which version of sails-orientdb are you using?

**Comment by gmchaturvedi1** [comment]
show:function(req,res,next){
    User.findOne(req.param('id'),function(err,user){
      if (err) return next(err);
      if(!user) return next();
      res.view({
        user:user
      });
    });
  }

**Comment by dmarcelino** [comment]
can you place `console.log('id:', req.param('id'));` just before `User.findOne` and tell us what you see on the console?

Which version of sails-orientdb are you using?

**Comment by gmchaturvedi1** [comment]
id: undefined

**Comment by dmarcelino** [comment]
That explains why you are not getting any results.

**Comment by gmchaturvedi1** [comment]
what should i do

**Comment by dmarcelino** [comment]
@gmchaturvedi1, your issue is not related to sails-orientdb you need to debug your application and investigate why you are getting an `undefined` id at that point. The only tip I can give you is that if you are passing and id like `#1:1` from the client as a `get` param you will have to first encode it with [`encodeURIComponent()`](http://www.w3schools.com/jsref/jsref_encodeURIComponent.asp). Good luck!

**Comment by gmchaturvedi1** [comment]
i found the problem that findone method is not working sails orientdb with the $id but when i am using only find method it is working.

**Comment by dmarcelino** [comment]
@gmchaturvedi1, I'm afraid you are mistaken. Considering what you've told us above, your id is `undefined` which is not a valid argument for `findOne()`.

sails-orientdb does support `findOne(id)`, there is an [automated test for this scenario](https://github.com/balderdashy/waterline-adapter-tests/blob/master/interfaces/semantic/findOne.test.js#L52):
``` javascript
    it('should work with just an id passed in', function(done) {
      Semantic.User.findOne(id, function(err, user) {
        assert(!err);
        assert(user.first_name === 'findOne test');
        done();
      });
    });
````
and sails-orientdb passes it.

The reason why `find()` is working for you is because `find(undefined)` returns all records for a given collection.

You can read more about the differences between `find()` and `findOne()` on the [Waterline Documentation](https://github.com/balderdashy/waterline-docs/blob/159a7ad89df0d47ff3c16e61456766245889ffbb/query-methods.md#find-criteria-callback-)
